title: Mescha Destianna # your name (or website title) here
photo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! Thank you for coming to my page. I'm an aspiring Data Professional with years of professional experiences as an engineer in the energy industry.
  <br><br>
  This portfolio website is intended to showcase personal projects related to data analytics which demonstrate some of the technical skills for a career transition to an Analyst role. Kindly reach me out for any inputs or opportunities.
  <br><br>
  
  <a href="https://www.linkedin.com/in/meschadestianna/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
